/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  StakingTokenDeployer,
  StakingTokenDeployerInterface,
} from "../StakingTokenDeployer";

const _abi = [
  {
    inputs: [],
    name: "parameters",
    outputs: [
      {
        internalType: "address",
        name: "factory",
        type: "address",
      },
      {
        internalType: "address",
        name: "stakingPoolAddress",
        type: "address",
      },
      {
        internalType: "address",
        name: "stakingPoolId",
        type: "address",
      },
      {
        internalType: "string",
        name: "name",
        type: "string",
      },
      {
        internalType: "string",
        name: "symbol",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class StakingTokenDeployer__factory {
  static readonly abi = _abi;
  static createInterface(): StakingTokenDeployerInterface {
    return new utils.Interface(_abi) as StakingTokenDeployerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): StakingTokenDeployer {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as StakingTokenDeployer;
  }
}
