/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface IQuantumPortalStakeInterface extends ethers.utils.Interface {
  functions: {
    "STAKE_ID()": FunctionFragment;
    "delegatedStakeOf(address)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "STAKE_ID", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "delegatedStakeOf",
    values: [string]
  ): string;

  decodeFunctionResult(functionFragment: "STAKE_ID", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "delegatedStakeOf",
    data: BytesLike
  ): Result;

  events: {};
}

export class IQuantumPortalStake extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IQuantumPortalStakeInterface;

  functions: {
    STAKE_ID(overrides?: CallOverrides): Promise<[string]>;

    delegatedStakeOf(
      actor: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;
  };

  STAKE_ID(overrides?: CallOverrides): Promise<string>;

  delegatedStakeOf(
    actor: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    STAKE_ID(overrides?: CallOverrides): Promise<string>;

    delegatedStakeOf(
      actor: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    STAKE_ID(overrides?: CallOverrides): Promise<BigNumber>;

    delegatedStakeOf(
      actor: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    STAKE_ID(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    delegatedStakeOf(
      actor: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
