/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  TokenReceivable,
  TokenReceivableInterface,
} from "../TokenReceivable";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "inventory",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class TokenReceivable__factory {
  static readonly abi = _abi;
  static createInterface(): TokenReceivableInterface {
    return new utils.Interface(_abi) as TokenReceivableInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): TokenReceivable {
    return new Contract(address, _abi, signerOrProvider) as TokenReceivable;
  }
}
