/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface IBridgePoolInterface extends ethers.utils.Interface {
  functions: {
    "addLiquidity(address,address)": FunctionFragment;
    "liquidity(address,address)": FunctionFragment;
    "removeLiquidity(address,address,uint256,uint256,address)": FunctionFragment;
    "removeLiquidityIfPossible(address,address,uint256)": FunctionFragment;
    "removeLiquiditySigned(address,address,uint256,uint32,bytes32,bytes)": FunctionFragment;
    "swap(address,address,uint256,address,address,address,address)": FunctionFragment;
    "withdrawSigned(address,address,uint256,address,uint32,bytes32,bytes)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "addLiquidity",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "liquidity",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "removeLiquidity",
    values: [string, string, BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "removeLiquidityIfPossible",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "removeLiquiditySigned",
    values: [string, string, BigNumberish, BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "swap",
    values: [string, string, BigNumberish, string, string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawSigned",
    values: [
      string,
      string,
      BigNumberish,
      string,
      BigNumberish,
      BytesLike,
      BytesLike
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "addLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "liquidity", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeLiquidityIfPossible",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeLiquiditySigned",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "swap", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawSigned",
    data: BytesLike
  ): Result;

  events: {};
}

export class IBridgePool extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IBridgePoolInterface;

  functions: {
    addLiquidity(
      to: string,
      token: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    liquidity(
      token: string,
      liquidityAdder: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    removeLiquidity(
      to: string,
      token: string,
      amount: BigNumberish,
      targetNetwork: BigNumberish,
      targetToken: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    removeLiquidityIfPossible(
      to: string,
      token: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    removeLiquiditySigned(
      token: string,
      payee: string,
      amount: BigNumberish,
      sourceChainId: BigNumberish,
      txId: BytesLike,
      multiSignature: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    swap(
      to: string,
      token: string,
      targetNetwork: BigNumberish,
      targetToken: string,
      swapTargetTokenTo: string,
      targetAddress: string,
      originToken: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    withdrawSigned(
      token: string,
      payee: string,
      amount: BigNumberish,
      swapToToken: string,
      sourceChainId: BigNumberish,
      swapTxId: BytesLike,
      multiSignature: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  addLiquidity(
    to: string,
    token: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  liquidity(
    token: string,
    liquidityAdder: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  removeLiquidity(
    to: string,
    token: string,
    amount: BigNumberish,
    targetNetwork: BigNumberish,
    targetToken: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  removeLiquidityIfPossible(
    to: string,
    token: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  removeLiquiditySigned(
    token: string,
    payee: string,
    amount: BigNumberish,
    sourceChainId: BigNumberish,
    txId: BytesLike,
    multiSignature: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  swap(
    to: string,
    token: string,
    targetNetwork: BigNumberish,
    targetToken: string,
    swapTargetTokenTo: string,
    targetAddress: string,
    originToken: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  withdrawSigned(
    token: string,
    payee: string,
    amount: BigNumberish,
    swapToToken: string,
    sourceChainId: BigNumberish,
    swapTxId: BytesLike,
    multiSignature: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    addLiquidity(
      to: string,
      token: string,
      overrides?: CallOverrides
    ): Promise<void>;

    liquidity(
      token: string,
      liquidityAdder: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    removeLiquidity(
      to: string,
      token: string,
      amount: BigNumberish,
      targetNetwork: BigNumberish,
      targetToken: string,
      overrides?: CallOverrides
    ): Promise<void>;

    removeLiquidityIfPossible(
      to: string,
      token: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    removeLiquiditySigned(
      token: string,
      payee: string,
      amount: BigNumberish,
      sourceChainId: BigNumberish,
      txId: BytesLike,
      multiSignature: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    swap(
      to: string,
      token: string,
      targetNetwork: BigNumberish,
      targetToken: string,
      swapTargetTokenTo: string,
      targetAddress: string,
      originToken: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    withdrawSigned(
      token: string,
      payee: string,
      amount: BigNumberish,
      swapToToken: string,
      sourceChainId: BigNumberish,
      swapTxId: BytesLike,
      multiSignature: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    addLiquidity(
      to: string,
      token: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    liquidity(
      token: string,
      liquidityAdder: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    removeLiquidity(
      to: string,
      token: string,
      amount: BigNumberish,
      targetNetwork: BigNumberish,
      targetToken: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    removeLiquidityIfPossible(
      to: string,
      token: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    removeLiquiditySigned(
      token: string,
      payee: string,
      amount: BigNumberish,
      sourceChainId: BigNumberish,
      txId: BytesLike,
      multiSignature: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    swap(
      to: string,
      token: string,
      targetNetwork: BigNumberish,
      targetToken: string,
      swapTargetTokenTo: string,
      targetAddress: string,
      originToken: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    withdrawSigned(
      token: string,
      payee: string,
      amount: BigNumberish,
      swapToToken: string,
      sourceChainId: BigNumberish,
      swapTxId: BytesLike,
      multiSignature: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addLiquidity(
      to: string,
      token: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    liquidity(
      token: string,
      liquidityAdder: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    removeLiquidity(
      to: string,
      token: string,
      amount: BigNumberish,
      targetNetwork: BigNumberish,
      targetToken: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    removeLiquidityIfPossible(
      to: string,
      token: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    removeLiquiditySigned(
      token: string,
      payee: string,
      amount: BigNumberish,
      sourceChainId: BigNumberish,
      txId: BytesLike,
      multiSignature: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    swap(
      to: string,
      token: string,
      targetNetwork: BigNumberish,
      targetToken: string,
      swapTargetTokenTo: string,
      targetAddress: string,
      originToken: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    withdrawSigned(
      token: string,
      payee: string,
      amount: BigNumberish,
      swapToToken: string,
      sourceChainId: BigNumberish,
      swapTxId: BytesLike,
      multiSignature: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
