/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IQuantumPortalMinerMgr,
  IQuantumPortalMinerMgrInterface,
} from "../IQuantumPortalMinerMgr";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "msgHash",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "salt",
        type: "bytes32",
      },
      {
        internalType: "uint64",
        name: "expiry",
        type: "uint64",
      },
      {
        internalType: "bytes",
        name: "multiSig",
        type: "bytes",
      },
    ],
    name: "extractMinerAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "miningStake",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "miner",
        type: "address",
      },
      {
        internalType: "bytes32",
        name: "blockHash",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "beneficiary",
        type: "address",
      },
    ],
    name: "slashMinerForFraud",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "msgHash",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "salt",
        type: "bytes32",
      },
      {
        internalType: "uint64",
        name: "expiry",
        type: "uint64",
      },
      {
        internalType: "bytes",
        name: "signature",
        type: "bytes",
      },
      {
        internalType: "uint256",
        name: "msgValue",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "minStakeAllowed",
        type: "uint256",
      },
    ],
    name: "verifyMinerSignature",
    outputs: [
      {
        internalType: "enum IQuantumPortalMinerMgr.ValidationResult",
        name: "res",
        type: "uint8",
      },
      {
        internalType: "address",
        name: "signer",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IQuantumPortalMinerMgr__factory {
  static readonly abi = _abi;
  static createInterface(): IQuantumPortalMinerMgrInterface {
    return new utils.Interface(_abi) as IQuantumPortalMinerMgrInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IQuantumPortalMinerMgr {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IQuantumPortalMinerMgr;
  }
}
